name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Create launcher script
        shell: powershell
        run: |
          @"
          import sys
          import eventeditor.__main__ as entry
          if __name__ == '__main__':
              entry.main()
          "@ | Set-Content -Path launcher.py -NoNewline

      - name: Build EXE with PyInstaller
        shell: powershell
        run: >
          pyinstaller --noconfirm --windowed --name EventEditor
          --paths .
          --collect-all eventeditor
          --collect-all evfl
          --add-data "eventeditor/assets;eventeditor/assets"
          --hidden-import PyQt5.QtWebEngineWidgets
          launcher.py

      - name: Compute build id
        shell: bash
        run: echo "BUILD_ID=${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Rename output folder
        shell: powershell
        run: |
          Rename-Item -Path dist/EventEditor -NewName ("EventEditor-" + $env:BUILD_ID)
          Set-Content -Path ("dist/EventEditor-" + $env:BUILD_ID + "/BUILD_INFO.txt") -Value ("BUILD_ID=" + $env:BUILD_ID)

      - name: Show build outputs
        shell: powershell
        run: |
          Get-ChildItem -Recurse ("dist/EventEditor-" + $env:BUILD_ID) | ForEach-Object { $_.FullName }

      - name: Remove any stray zips
        shell: powershell
        run: |
          Get-ChildItem -Path dist -Filter *.zip -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EventEditor-Windows-${{ env.BUILD_ID }}
          path: dist/EventEditor-${{ env.BUILD_ID }}