name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: powershell
        run: >
          pyinstaller --noconfirm --windowed --name EventEditor
          --paths .
          --add-data "eventeditor/assets;eventeditor/assets"
          --hidden-import PyQt5.QtWebEngineWidgets
          eventeditor/__main__.py

      - name: Archive artifact
        run: |
          powershell -Command "Compress-Archive -Path 'dist/EventEditor/*' -DestinationPath 'EventEditor-Windows.zip'"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EventEditor-Windows
          path: EventEditor-Windows.zip